/** Canonical English URL slugs for Hebrew catalog category names from Base44. */
export const CATEGORY_SLUGS: Record<string, string> = {
  "מקררים": "refrigerators",
  "מקפיאים": "freezers",
  "מכונות כביסה": "washing-machines",
  "מייבשי כביסה": "dryers",
  "מדיחי כלים": "dishwashers",
  "תנורים": "ovens",
  "כיריים": "cooktops",
  "קולטי אדים": "range-hoods",
  "מיקרוגלים": "microwaves",
  "טלוויזיות": "tvs",
  "מזגנים": "air-conditioners",
  "מוצרי חשמל קטנים": "small-appliances",
  "אביזרים נלווים": "accessories",
  אביזרים: "accessories",
  אוזניות: "headphones",
  בלנדרים: "blenders",
  "גריל חשמלי": "electric-grills",
  "טוסטר אובן": "toaster-ovens",
  "טוסטר גריל לחיצה": "panini-grills",
  טלפונים: "phones",
  "כיסא מנהל/גיימר": "gaming-chairs",
  "כירות בישול": "hot-plates",
  מאווררים: "fans",
  "מברשת שיניים": "electric-toothbrushes",
  מגברים: "amplifiers",
  מגהצים: "hair-straighteners",
  "מחבתות חשמליות": "electric-pans",
  "מחליקי שיער": "hair-stylers",
  "מטהר אוויר": "air-purifiers",
  "מטחנות בשר": "meat-grinders",
  "מטחנות קפה": "coffee-grinders",
  מיחמים: "humidifiers",
  "מייבשי שיער": "hair-dryers",
  מיקסרים: "mixers",
  "מיקרוגל משולב תנור": "microwave-ovens",
  "מכונות גילוח": "shavers",
  "מכונות קפה": "coffee-machines",
  "מכונות תספורת": "hair-clippers",
  "מכונת גלידה": "ice-cream-makers",
  "מכשיר אפילציה": "epilators",
  "מכשיר לניקוי בקיטור": "steam-cleaners",
  "מכשיר פופ קורן": "popcorn-makers",
  "מכשירי אפיה (וופל, פנקייק, דונאטס)": "waffle-makers",
  "מכשירי קרח": "ice-makers",
  ממירים: "converters",
  מסחטות: "juicers",
  "מעבדי מזון": "food-processors",
  "מערכות סטריאו": "stereo-systems",
  "מפזרי חום": "space-heaters",
  מצנמים: "toasters",
  "מצנני אוויר": "air-coolers",
  "מקציף חלב": "milk-frothers",
  "מקרני קול": "soundbars",
  מקרנים: "projectors",
  "מקררי יין": "wine-coolers",
  משקל: "scales",
  "מתקני מים": "water-dispensers",
  "נפה חשמלית": "electric-blankets",
  "סדין חימום": "heating-pads",
  "סיר בישול": "cooking-pots",
  "סירי גריל": "grill-pans",
  "סירי טיגון באוויר": "air-fryers",
  "סירי טיגון בשמן": "deep-fryers",
  "פלטות שבת": "shabbat-hot-plates",
  קומקומים: "kettles",
  קוצצים: "trimmers",
  "קטלן יתושים": "mosquito-killers",
  "רדיו וטרנזיסטורים": "radios",
  רמקולים: "speakers",
  שואבים: "vacuum-cleaners",
  "שואבים רובוטיים": "robot-vacuums",
  "תאורת חרום": "emergency-lighting",
  "תנורי חימום": "heaters",
};
