import type { Base44Product } from "@/types/api";

/**
 * Fallback catalog used only when the live Base44 API is unreachable
 * (network failure, rate limit, etc.), so the site never shows a
 * broken/empty catalog. This is NOT real inventory data.
 */
export const MOCK_CATALOG: Base44Product[] = [
  {
    model_number: "RF-2201B",
    name: "מקרר 4 דלתות נירוסטה",
    brand: "Samsung",
    category: "מקררים",
    image_url: null,
    origin_country: "קוריאה",
    technical_specifications: "נפח כולל: 550 ליטר; דירוג אנרגטי: A+; רמת רעש: 39dB",
    product_capabilities: "מקרר ללא כפור; מערכת קירור דיגיטלית; מתאים למטבחים גדולים",
    is_available: true,
  },
  {
    model_number: "RF-1180S",
    name: "מקרר טופ פריזר",
    brand: "LG",
    category: "מקררים",
    image_url: null,
    origin_country: "קוריאה",
    technical_specifications: "נפח כולל: 380 ליטר; דירוג אנרגטי: A++",
    product_capabilities: "מקפיא עליון; מדפי זכוכית מחוסמת",
    is_available: true,
  },
  {
    model_number: "WM-7300K",
    name: "מכונת כביסה 9 ק\"ג",
    brand: "Samsung",
    category: "מכונות כביסה",
    image_url: null,
    origin_country: "קוריאה",
    technical_specifications: "קיבולת: 9 ק\"ג; סל\"ד סחיטה: 1400; דירוג אנרגטי: A",
    product_capabilities: "טכנולוגיית מנוע דיגיטלי אינוורטר; תוכנית סניטציה",
    is_available: true,
  },
  {
    model_number: "WM-6100L",
    name: "מכונת כביסה 8 ק\"ג",
    brand: "LG",
    category: "מכונות כביסה",
    image_url: null,
    origin_country: "קוריאה",
    technical_specifications: "קיבולת: 8 ק\"ג; סל\"ד סחיטה: 1200",
    product_capabilities: "תוף ישיר בהנעה; תוכנית כביסה מהירה",
    is_available: false,
  },
  {
    model_number: "DR-5400",
    name: "מייבש כביסה קונדנסור 8 ק\"ג",
    brand: "Electrolux",
    category: "מייבשי כביסה",
    image_url: null,
    origin_country: "שוודיה",
    technical_specifications: "קיבולת: 8 ק\"ג; דירוג אנרגטי: B",
    product_capabilities: "חיישן לחות; תוף עדין לבדים",
    is_available: true,
  },
  {
    model_number: "DW-9012",
    name: "מדיח כלים אינטגרלי 14 מקומות",
    brand: "Bosch",
    category: "מדיחי כלים",
    image_url: null,
    origin_country: "גרמניה",
    technical_specifications: "14 מקומות אכילה; רמת רעש: 44dB; דירוג אנרגטי: A++",
    product_capabilities: "תוכנית אקו; ייבוש בסיוע אדים",
    is_available: true,
  },
  {
    model_number: "EOH3101K",
    name: "תנור בנוי דיגיטלי שחור",
    brand: "Electrolux",
    category: "תנורים",
    image_url: null,
    origin_country: "איטליה",
    technical_specifications: "נפח תא אפייה: 72 ליטר; דירוג אנרגטי: A",
    product_capabilities: "מערכת טורבו אקטיבי 4D Even Cooking; ניקוי פירוליטי",
    is_available: true,
  },
  {
    model_number: "OV-3350",
    name: "תנור בנוי נירוסטה",
    brand: "Sharp",
    category: "תנורים",
    image_url: null,
    origin_country: "יפן",
    technical_specifications: "נפח תא אפייה: 65 ליטר",
    product_capabilities: "8 תוכניות אפייה; טיימר דיגיטלי",
    is_available: true,
  },
  {
    model_number: "CK-4100",
    name: "כיריים גז 5 מבערים נירוסטה",
    brand: "Sharp",
    category: "כיריים",
    image_url: null,
    origin_country: "יפן",
    technical_specifications: "5 מבערים; משטח נירוסטה",
    product_capabilities: "הצתה אלקטרונית; שסתומי בטיחות לכיבוי גז",
    is_available: true,
  },
  {
    model_number: "CK-IND200",
    name: "כיריים אינדוקציה 4 אזורים",
    brand: "Bosch",
    category: "כיריים",
    image_url: null,
    origin_country: "גרמניה",
    technical_specifications: "4 אזורי בישול; משטח זכוכית קרמית",
    product_capabilities: "בקרת מגע; פונקציית בוסטר",
    is_available: false,
  },
  {
    model_number: "HD-6600",
    name: "קולט אדים נירוסטה 90 ס\"מ",
    brand: "Electrolux",
    category: "קולטי אדים",
    image_url: null,
    origin_country: "שוודיה",
    technical_specifications: "רוחב: 90 ס\"מ; רמת ספיקה: 650 מ\"ק לשעה",
    product_capabilities: "3 מהירויות שאיבה; תאורת LED",
    is_available: true,
  },
  {
    model_number: "MW-2050",
    name: "מיקרוגל דיגיטלי 25 ליטר",
    brand: "LG",
    category: "מיקרוגלים",
    image_url: null,
    origin_country: "קוריאה",
    technical_specifications: "נפח: 25 ליטר; הספק: 900W",
    product_capabilities: "תוכניות אוטומטיות; חימום בשילוב גריל",
    is_available: true,
  },
  {
    model_number: "TV-5501U",
    name: "טלוויזיה חכמה 55 אינץ' 4K",
    brand: "TCL",
    category: "טלוויזיות",
    image_url: null,
    origin_country: "סין",
    technical_specifications: "גודל מסך: 55 אינץ'; רזולוציה: 4K UHD",
    product_capabilities: "מערכת הפעלה חכמה; תמיכה ב-HDR",
    is_available: true,
  },
  {
    model_number: "TV-6502Q",
    name: "טלוויזיה חכמה 65 אינץ' QLED",
    brand: "Samsung",
    category: "טלוויזיות",
    image_url: null,
    origin_country: "קוריאה",
    technical_specifications: "גודל מסך: 65 אינץ'; טכנולוגיה: QLED",
    product_capabilities: "עיבוד תמונה מתקדם; חיבוריות Smart Hub",
    is_available: true,
  },
  {
    model_number: "AC-1200I",
    name: "מזגן עילי אינוורטר 1 כ\"ס",
    brand: "LG",
    category: "מזגנים",
    image_url: null,
    origin_country: "קוריאה",
    technical_specifications: "הספק: 1 כ\"ס; טכנולוגיית אינוורטר",
    product_capabilities: "פעולת קירור וחימום; מצב שינה חסכוני",
    is_available: true,
  },
  {
    model_number: "AC-2400I",
    name: "מזגן עילי אינוורטר 2 כ\"ס",
    brand: "Electrolux",
    category: "מזגנים",
    image_url: null,
    origin_country: "שוודיה",
    technical_specifications: "הספק: 2 כ\"ס; טכנולוגיית אינוורטר",
    product_capabilities: "סינון אוויר רב-שכבתי; בקרה מרחוק",
    is_available: false,
  },
  {
    model_number: "FR-3300",
    name: "מקפיא ארונית 5 מגירות",
    brand: "Sharp",
    category: "מקפיאים",
    image_url: null,
    origin_country: "יפן",
    technical_specifications: "נפח: 300 ליטר; 5 מגירות",
    product_capabilities: "מערכת נו-פרוסט; נעילת ילדים",
    is_available: true,
  },
  {
    model_number: "KT-8801",
    name: "קומקום חשמלי נירוסטה",
    brand: "Sharp",
    category: "מוצרי חשמל קטנים",
    image_url: null,
    origin_country: "יפן",
    technical_specifications: "נפח: 1.7 ליטר; הספק: 2200W",
    product_capabilities: "כיבוי אוטומטי; בסיס מסתובב 360 מעלות",
    is_available: true,
  },
  {
    model_number: "MX-1200",
    name: "מיקסר מטבח רב-תכליתי",
    brand: "Bosch",
    category: "מוצרי חשמל קטנים",
    image_url: null,
    origin_country: "גרמניה",
    technical_specifications: "הספק: 1000W; קערה: 4.8 ליטר",
    product_capabilities: "מגוון מהירויות; אביזרים נלווים ללישה וטריפה",
    is_available: true,
  },
  {
    model_number: "VF-500",
    name: "מסנן מים למקרר — תחליף מקורי",
    brand: "Samsung",
    category: "אביזרים נלווים",
    image_url: null,
    origin_country: "קוריאה",
    technical_specifications: "תואם לדגמי מקרר עם מסנן מים פנימי",
    product_capabilities: "מסנן פחמן פעיל; מפחית סחף ואבנית",
    is_available: true,
  },
];
