import { GUIDES, type Guide } from "@/content/guides";
import type { Product } from "@/types/product";
import type { Locale } from "@/lib/i18n/locales";
import guidesEn from "@/content/i18n/translations/guides.en.json";
import guidesRu from "@/content/i18n/translations/guides.ru.json";
import catalogEn from "@/content/i18n/translations/catalog.en.json";
import catalogRu from "@/content/i18n/translations/catalog.ru.json";
import { NATIVE_RU_GUIDES, type NativeGuide } from "@/content/i18n/native/guides.ru";

/**
 * Runtime lookups into the committed machine-translation stores
 * (content/i18n/translations/, generated by `npm run translate`).
 *
 * Fallback rule everywhere: if a translation is missing or its shape no
 * longer matches the source, render the original Hebrew text.
 */

interface GuideTranslation {
  title: string;
  description: string;
  sections: { heading?: string; paragraphs: string[] }[];
  faq?: { question: string; answer: string }[];
}

interface CatalogStore {
  products: Record<string, { name: string; description: string }>;
  categories: Record<string, { name: string }>;
}

const GUIDE_STORES: Record<"en" | "ru", { entries: Record<string, GuideTranslation> }> = {
  en: guidesEn as never,
  ru: guidesRu as never,
};

const CATALOG_STORES: Record<"en" | "ru", CatalogStore> = {
  en: catalogEn as never,
  ru: catalogRu as never,
};

/**
 * Whether a real translation exists for a guide in a locale.
 *
 * `localizeGuide` falls back to Hebrew when a translation is missing, which is
 * right for a reader who landed there — but a page of Hebrew prose served
 * under `hreflang="ru"` is a page Google is entitled to treat as a mistake.
 * Callers use this to noindex the untranslated variant until the translation
 * job has run, rather than shipping it and hoping.
 */
/**
 * Hand-written editions win over machine translation. They are not held to the
 * section-for-section shape check below, because they are written for the
 * locale rather than translated from Hebrew and can be structured differently.
 */
const NATIVE_GUIDES: Record<"en" | "ru", Record<string, NativeGuide>> = {
  en: {},
  ru: NATIVE_RU_GUIDES,
};

export function hasNativeGuide(slug: string, locale: Locale): boolean {
  return locale !== "he" && Boolean(NATIVE_GUIDES[locale][slug]);
}

export function hasGuideTranslation(slug: string, locale: Locale): boolean {
  if (locale === "he") return true;
  if (NATIVE_GUIDES[locale][slug]) return true;
  const guideTranslation = GUIDE_STORES[locale].entries[slug];
  if (!guideTranslation?.title) return false;

  // A stored translation is not automatically a usable one. `localizeGuide`
  // refuses any entry whose section count no longer matches the source and
  // falls back to Hebrew — so an entry that has drifted would otherwise be
  // advertised via hreflang, submitted in the sitemap and left indexable
  // while the page it points at renders Hebrew prose. That is precisely the
  // failure this function exists to prevent, so it applies the same test.
  //
  // Drift is normal: rewriting a guide changes its shape, and the
  // translation job runs separately. The page stays reachable; it just stops
  // claiming to be translated until `npm run translate` catches up.
  const source = GUIDES.find((guide) => guide.slug === slug);
  if (!source) return false;
  return guideTranslation.sections.length === source.sections.length;
}

export function localizeGuide(guide: Guide, locale: Locale): Guide {
  if (locale === "he") return guide;
  const native = NATIVE_GUIDES[locale][guide.slug];
  if (native) {
    return {
      ...guide,
      title: native.title,
      description: native.description,
      answer: native.answer,
      sections: native.sections,
      faq: native.faq ?? guide.faq,
    };
  }
  // The short answer is written in one language and is never machine-translated,
  // so it must not ride along on the spread below. It did, once: the English
  // edition of the 65-inch guide rendered "Short answer" over Hebrew text. Only
  // a hand-written edition (handled above) carries an answer into a locale.
  const { answer: _hebrewAnswer, ...base } = guide;
  void _hebrewAnswer;
  const t = GUIDE_STORES[locale].entries[guide.slug];
  if (!t || t.sections.length !== guide.sections.length) return base;
  return {
    ...base,
    title: t.title || guide.title,
    description: t.description || guide.description,
    sections: guide.sections.map((section, i) => ({
      heading: t.sections[i]?.heading ?? section.heading,
      paragraphs:
        t.sections[i]?.paragraphs.length === section.paragraphs.length
          ? t.sections[i].paragraphs
          : section.paragraphs,
    })),
    faq:
      guide.faq && t.faq && t.faq.length === guide.faq.length
        ? t.faq
        : guide.faq,
  };
}

/**
 * Whether a real translation exists for a product in a locale.
 *
 * 90 of the 891 catalog products have no entry, and `localizeProduct` falls
 * back to Hebrew — which now means an English URL serving a Hebrew name with
 * an English suffix bolted on. Same rule as guides: keep the page reachable,
 * keep it out of the index and out of the hreflang cluster until the
 * translation job has run.
 */
export function hasProductTranslation(modelNumber: string, locale: Locale): boolean {
  if (locale === "he") return true;
  return Boolean(CATALOG_STORES[locale].products[modelNumber]?.name);
}

export function localizeProduct(product: Product, locale: Locale): Product {
  if (locale === "he") return product;
  const store = CATALOG_STORES[locale];
  const t = store.products[product.modelNumber];
  const category = product.categorySlug ? store.categories[product.categorySlug]?.name : undefined;
  if (!t && !category) return product;
  return {
    ...product,
    name: t?.name || product.name,
    description: t?.description || product.description,
    category: category ?? product.category,
  };
}

export function localizeProducts(products: Product[], locale: Locale): Product[] {
  if (locale === "he") return products;
  return products.map((p) => localizeProduct(p, locale));
}

export function localizeCategoryName(categorySlug: string | null, fallback: string | null, locale: Locale): string | null {
  if (locale === "he" || !categorySlug) return fallback;
  return CATALOG_STORES[locale].categories[categorySlug]?.name ?? fallback;
}
