import type { Guide } from "@/content/guides";
import type { Product } from "@/types/product";
import type { Locale } from "@/lib/i18n/locales";
import guidesEn from "@/content/i18n/translations/guides.en.json";
import guidesRu from "@/content/i18n/translations/guides.ru.json";
import catalogEn from "@/content/i18n/translations/catalog.en.json";
import catalogRu from "@/content/i18n/translations/catalog.ru.json";

/**
 * Runtime lookups into the committed machine-translation stores
 * (content/i18n/translations/, generated by `npm run translate`).
 *
 * Fallback rule everywhere: if a translation is missing or its shape no
 * longer matches the source, render the original Hebrew text.
 */

interface GuideTranslation {
  title: string;
  description: string;
  sections: { heading?: string; paragraphs: string[] }[];
  faq?: { question: string; answer: string }[];
}

interface CatalogStore {
  products: Record<string, { name: string; description: string }>;
  categories: Record<string, { name: string }>;
}

const GUIDE_STORES: Record<"en" | "ru", { entries: Record<string, GuideTranslation> }> = {
  en: guidesEn as never,
  ru: guidesRu as never,
};

const CATALOG_STORES: Record<"en" | "ru", CatalogStore> = {
  en: catalogEn as never,
  ru: catalogRu as never,
};

export function localizeGuide(guide: Guide, locale: Locale): Guide {
  if (locale === "he") return guide;
  const t = GUIDE_STORES[locale].entries[guide.slug];
  if (!t || t.sections.length !== guide.sections.length) return guide;
  return {
    ...guide,
    title: t.title || guide.title,
    description: t.description || guide.description,
    sections: guide.sections.map((section, i) => ({
      heading: t.sections[i]?.heading ?? section.heading,
      paragraphs:
        t.sections[i]?.paragraphs.length === section.paragraphs.length
          ? t.sections[i].paragraphs
          : section.paragraphs,
    })),
    faq:
      guide.faq && t.faq && t.faq.length === guide.faq.length
        ? t.faq
        : guide.faq,
  };
}

export function localizeProduct(product: Product, locale: Locale): Product {
  if (locale === "he") return product;
  const store = CATALOG_STORES[locale];
  const t = store.products[product.modelNumber];
  const category = product.categorySlug ? store.categories[product.categorySlug]?.name : undefined;
  if (!t && !category) return product;
  return {
    ...product,
    name: t?.name || product.name,
    description: t?.description || product.description,
    category: category ?? product.category,
  };
}

export function localizeProducts(products: Product[], locale: Locale): Product[] {
  if (locale === "he") return products;
  return products.map((p) => localizeProduct(p, locale));
}

export function localizeCategoryName(categorySlug: string | null, fallback: string | null, locale: Locale): string | null {
  if (locale === "he" || !categorySlug) return fallback;
  return CATALOG_STORES[locale].categories[categorySlug]?.name ?? fallback;
}
